
import sys
import os
import viou_tracker as viou
import scipy.io

print(sys.argv)

if len(sys.argv) < 10:
	print("Usage: octave_wrapper.py detectionsFile sigma_l sigma_h sigma_iou t_min ttl tracker_type keep_upper_height_ratio seqName")
	sys.exit(2)

d = scipy.io.loadmat(sys.argv[1])
detections = d['detects']
sigma_l = float(sys.argv[2])
sigma_h = float(sys.argv[3])
sigma_iou = float(sys.argv[4])
t_min = float(sys.argv[5])
ttl = float(sys.argv[6])
tracker_type = (sys.argv[7])
keep_upper_height_ratio = float(sys.argv[8])

"""(leftover arguments from iou[unused in VIOU])
sigma_iou = float(sys.argv[3])
sigma_p = int(sys.argv[4])
sigma_len = int(sys.argv[5])
sf = int(sys.argv[6])
skip_frames = True
if sf == 0:
	skip_frames = False
n_skip = int(sys.argv[7])
"""

seq_name = sys.argv[9]
print("Seq_name: ", seq_name)

frames_path= "../../DETRAC-images/" + seq_name + '/' 
#frames_path='..\..\DETRAC-images\MVI_41073_0\\' #Car Video

detections = d['detects']

#CONFIG-1-MEDIANFLOW
"""
sigma_l=0.9
sigma_h=0.98
sigma_iou=0.1
t_min=23
ttl=8
tracker_type='MEDIANFLOW'
keep_upper_height_ratio=1.0
"""

#CONFIG-2-MEDIANFLOW
"""
sigma_l=0.7
sigma_h=0.98
sigma_iou=0.2
t_min=19
ttl=10
tracker_type='MEDIANFLOW'
keep_upper_height_ratio=1.0
"""

#CONFIG-Make-it-work
"""
sigma_l=0.0
sigma_h=0.5
sigma_iou=0.2
t_min=19
ttl=10
tracker_type='MEDIANFLOW'
keep_upper_height_ratio=1.0
"""

speed, trackList = viou.track_viou_matlab_wrapper(frames_path, detections, sigma_l, sigma_h, sigma_iou, t_min, ttl, tracker_type, keep_upper_height_ratio)

"""
    Args:
         frames_path (str): path to ALL frames.
                            string must contain a placeholder like {:07d} to be replaced with the frame numbers.
         detections (list): list of detections per frame, usually generated by util.load_mot
         sigma_l (float): low detection threshold.
         sigma_h (float): high detection threshold.
         sigma_iou (float): IOU threshold.
         t_min (float): minimum track length in frames.
         ttl (float): maximum number of frames to perform visual tracking.
                      this can fill 'gaps' of up to 2*ttl frames (ttl times forward and backward).
         tracker_type (str): name of the visual tracker to use. see VisTracker for more details.
         keep_upper_height_ratio (float): float between 0.0 and 1.0 that determines the ratio of height of the object
                                          to track to the total height of the object used for visual tracking.
"""
scipy.io.savemat("results.mat", {"speed":speed, 'trackList':trackList})
